package modelo;
// Generated 20/05/2016 16:28:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Acta generated by hbm2java
 */
@Entity
@Table(name="acta"
    ,catalog="transito"
)
public class Acta  implements java.io.Serializable {


     private Integer idacta;
     private int idlicencia;
     private Date fechaacta;
     private String lugarinfraccion;
     private int idpersonal;
     private String observacionesacta;

    public Acta() {
    }

    public Acta(int idlicencia, Date fechaacta, String lugarinfraccion, int idpersonal, String observacionesacta) {
       this.idlicencia = idlicencia;
       this.fechaacta = fechaacta;
       this.lugarinfraccion = lugarinfraccion;
       this.idpersonal = idpersonal;
       this.observacionesacta = observacionesacta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idacta", unique=true, nullable=false)
    public Integer getIdacta() {
        return this.idacta;
    }
    
    public void setIdacta(Integer idacta) {
        this.idacta = idacta;
    }

    
    @Column(name="idlicencia", nullable=false)
    public int getIdlicencia() {
        return this.idlicencia;
    }
    
    public void setIdlicencia(int idlicencia) {
        this.idlicencia = idlicencia;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaacta", nullable=false, length=10)
    public Date getFechaacta() {
        return this.fechaacta;
    }
    
    public void setFechaacta(Date fechaacta) {
        this.fechaacta = fechaacta;
    }

    
    @Column(name="lugarinfraccion", nullable=false, length=150)
    public String getLugarinfraccion() {
        return this.lugarinfraccion;
    }
    
    public void setLugarinfraccion(String lugarinfraccion) {
        this.lugarinfraccion = lugarinfraccion;
    }

    
    @Column(name="idpersonal", nullable=false)
    public int getIdpersonal() {
        return this.idpersonal;
    }
    
    public void setIdpersonal(int idpersonal) {
        this.idpersonal = idpersonal;
    }

    
    @Column(name="observacionesacta", nullable=false, length=65535)
    public String getObservacionesacta() {
        return this.observacionesacta;
    }
    
    public void setObservacionesacta(String observacionesacta) {
        this.observacionesacta = observacionesacta;
    }




}


