package modelo;
// Generated 20/05/2016 16:28:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name="clase"
    ,catalog="transito"
)
public class Clase  implements java.io.Serializable {


     private Integer idclase;
     private String tipoclase;
     private String descripcionclase;

    public Clase() {
    }

    public Clase(String tipoclase, String descripcionclase) {
       this.tipoclase = tipoclase;
       this.descripcionclase = descripcionclase;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idclase", unique=true, nullable=false)
    public Integer getIdclase() {
        return this.idclase;
    }
    
    public void setIdclase(Integer idclase) {
        this.idclase = idclase;
    }

    
    @Column(name="tipoclase", nullable=false, length=10)
    public String getTipoclase() {
        return this.tipoclase;
    }
    
    public void setTipoclase(String tipoclase) {
        this.tipoclase = tipoclase;
    }

    
    @Column(name="descripcionclase", nullable=false, length=150)
    public String getDescripcionclase() {
        return this.descripcionclase;
    }
    
    public void setDescripcionclase(String descripcionclase) {
        this.descripcionclase = descripcionclase;
    }




}


