package modelo;
// Generated 20/05/2016 16:28:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Grua generated by hbm2java
 */
@Entity
@Table(name="grua"
    ,catalog="transito"
)
public class Grua  implements java.io.Serializable {


     private Integer idgrua;
     private String patentegrua;
     private String numerochasisgrua;
     private int numeromotorgrua;

    public Grua() {
    }

    public Grua(String patentegrua, String numerochasisgrua, int numeromotorgrua) {
       this.patentegrua = patentegrua;
       this.numerochasisgrua = numerochasisgrua;
       this.numeromotorgrua = numeromotorgrua;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idgrua", unique=true, nullable=false)
    public Integer getIdgrua() {
        return this.idgrua;
    }
    
    public void setIdgrua(Integer idgrua) {
        this.idgrua = idgrua;
    }

    
    @Column(name="patentegrua", nullable=false, length=100)
    public String getPatentegrua() {
        return this.patentegrua;
    }
    
    public void setPatentegrua(String patentegrua) {
        this.patentegrua = patentegrua;
    }

    
    @Column(name="numerochasisgrua", nullable=false, length=100)
    public String getNumerochasisgrua() {
        return this.numerochasisgrua;
    }
    
    public void setNumerochasisgrua(String numerochasisgrua) {
        this.numerochasisgrua = numerochasisgrua;
    }

    
    @Column(name="numeromotorgrua", nullable=false)
    public int getNumeromotorgrua() {
        return this.numeromotorgrua;
    }
    
    public void setNumeromotorgrua(int numeromotorgrua) {
        this.numeromotorgrua = numeromotorgrua;
    }




}


