package modelo;
// Generated 20/05/2016 16:28:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Licencias generated by hbm2java
 */
@Entity
@Table(name="licencias"
    ,catalog="transito"
)
public class Licencias  implements java.io.Serializable {


     private Integer idlicencias;
     private int nlicencias;
     private String apellidolic;
     private String nombrelic;
     private Date fechanacimientolic;
     private String domiciliolic;
     private String nacionalidadlic;
     private Date fechaemicionlic;
     private Date fechavencelic;
     private int idclase;
     private int puntoslic;
     private String gruposangrelic;
     private String estadolic;
     private String estadoadmlic;
     private Date fechaaltalic;

    public Licencias() {
    }

    public Licencias(int nlicencias, String apellidolic, String nombrelic, Date fechanacimientolic, String domiciliolic, String nacionalidadlic, Date fechaemicionlic, Date fechavencelic, int idclase, int puntoslic, String gruposangrelic, String estadolic, String estadoadmlic, Date fechaaltalic) {
       this.nlicencias = nlicencias;
       this.apellidolic = apellidolic;
       this.nombrelic = nombrelic;
       this.fechanacimientolic = fechanacimientolic;
       this.domiciliolic = domiciliolic;
       this.nacionalidadlic = nacionalidadlic;
       this.fechaemicionlic = fechaemicionlic;
       this.fechavencelic = fechavencelic;
       this.idclase = idclase;
       this.puntoslic = puntoslic;
       this.gruposangrelic = gruposangrelic;
       this.estadolic = estadolic;
       this.estadoadmlic = estadoadmlic;
       this.fechaaltalic = fechaaltalic;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idlicencias", unique=true, nullable=false)
    public Integer getIdlicencias() {
        return this.idlicencias;
    }
    
    public void setIdlicencias(Integer idlicencias) {
        this.idlicencias = idlicencias;
    }

    
    @Column(name="nlicencias", nullable=false)
    public int getNlicencias() {
        return this.nlicencias;
    }
    
    public void setNlicencias(int nlicencias) {
        this.nlicencias = nlicencias;
    }

    
    @Column(name="apellidolic", nullable=false, length=100)
    public String getApellidolic() {
        return this.apellidolic;
    }
    
    public void setApellidolic(String apellidolic) {
        this.apellidolic = apellidolic;
    }

    
    @Column(name="nombrelic", nullable=false, length=100)
    public String getNombrelic() {
        return this.nombrelic;
    }
    
    public void setNombrelic(String nombrelic) {
        this.nombrelic = nombrelic;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechanacimientolic", nullable=false, length=10)
    public Date getFechanacimientolic() {
        return this.fechanacimientolic;
    }
    
    public void setFechanacimientolic(Date fechanacimientolic) {
        this.fechanacimientolic = fechanacimientolic;
    }

    
    @Column(name="domiciliolic", nullable=false, length=150)
    public String getDomiciliolic() {
        return this.domiciliolic;
    }
    
    public void setDomiciliolic(String domiciliolic) {
        this.domiciliolic = domiciliolic;
    }

    
    @Column(name="nacionalidadlic", nullable=false, length=15)
    public String getNacionalidadlic() {
        return this.nacionalidadlic;
    }
    
    public void setNacionalidadlic(String nacionalidadlic) {
        this.nacionalidadlic = nacionalidadlic;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaemicionlic", nullable=false, length=10)
    public Date getFechaemicionlic() {
        return this.fechaemicionlic;
    }
    
    public void setFechaemicionlic(Date fechaemicionlic) {
        this.fechaemicionlic = fechaemicionlic;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechavencelic", nullable=false, length=10)
    public Date getFechavencelic() {
        return this.fechavencelic;
    }
    
    public void setFechavencelic(Date fechavencelic) {
        this.fechavencelic = fechavencelic;
    }

    
    @Column(name="idclase", nullable=false)
    public int getIdclase() {
        return this.idclase;
    }
    
    public void setIdclase(int idclase) {
        this.idclase = idclase;
    }

    
    @Column(name="puntoslic", nullable=false)
    public int getPuntoslic() {
        return this.puntoslic;
    }
    
    public void setPuntoslic(int puntoslic) {
        this.puntoslic = puntoslic;
    }

    
    @Column(name="gruposangrelic", nullable=false, length=10)
    public String getGruposangrelic() {
        return this.gruposangrelic;
    }
    
    public void setGruposangrelic(String gruposangrelic) {
        this.gruposangrelic = gruposangrelic;
    }

    
    @Column(name="estadolic", nullable=false, length=100)
    public String getEstadolic() {
        return this.estadolic;
    }
    
    public void setEstadolic(String estadolic) {
        this.estadolic = estadolic;
    }

    
    @Column(name="estadoadmlic", nullable=false, length=100)
    public String getEstadoadmlic() {
        return this.estadoadmlic;
    }
    
    public void setEstadoadmlic(String estadoadmlic) {
        this.estadoadmlic = estadoadmlic;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaaltalic", nullable=false, length=10)
    public Date getFechaaltalic() {
        return this.fechaaltalic;
    }
    
    public void setFechaaltalic(Date fechaaltalic) {
        this.fechaaltalic = fechaaltalic;
    }




}


