package modelo;
// Generated 20/05/2016 16:28:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu"
    ,catalog="transito"
)
public class Menu  implements java.io.Serializable {


     private Integer idmenu;
     private String nivel;

    public Menu() {
    }

    public Menu(String nivel) {
       this.nivel = nivel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmenu", unique=true, nullable=false)
    public Integer getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(Integer idmenu) {
        this.idmenu = idmenu;
    }

    
    @Column(name="nivel", nullable=false, length=100)
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }




}


