package modelo;
// Generated 20/05/2016 16:28:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Motovehiculo generated by hbm2java
 */
@Entity
@Table(name="motovehiculo"
    ,catalog="transito"
)
public class Motovehiculo  implements java.io.Serializable {


     private Integer idmotovehiculo;
     private String patentem;
     private String numerochasism;
     private String numeromotorm;

    public Motovehiculo() {
    }

    public Motovehiculo(String patentem, String numerochasism, String numeromotorm) {
       this.patentem = patentem;
       this.numerochasism = numerochasism;
       this.numeromotorm = numeromotorm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmotovehiculo", unique=true, nullable=false)
    public Integer getIdmotovehiculo() {
        return this.idmotovehiculo;
    }
    
    public void setIdmotovehiculo(Integer idmotovehiculo) {
        this.idmotovehiculo = idmotovehiculo;
    }

    
    @Column(name="patentem", nullable=false, length=100)
    public String getPatentem() {
        return this.patentem;
    }
    
    public void setPatentem(String patentem) {
        this.patentem = patentem;
    }

    
    @Column(name="numerochasism", nullable=false, length=100)
    public String getNumerochasism() {
        return this.numerochasism;
    }
    
    public void setNumerochasism(String numerochasism) {
        this.numerochasism = numerochasism;
    }

    
    @Column(name="numeromotorm", nullable=false, length=100)
    public String getNumeromotorm() {
        return this.numeromotorm;
    }
    
    public void setNumeromotorm(String numeromotorm) {
        this.numeromotorm = numeromotorm;
    }




}


