package modelo;
// Generated 20/05/2016 16:28:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="personal"
    ,catalog="transito"
)
public class Personal  implements java.io.Serializable {


     private Integer idpersonal;
     private int dnipersonal;
     private String apellidop;
     private String nombrep;
     private Date fechanacimientop;
     private String domiciliop;
     private String nacionalidadp;
     private Date fechaaltap;
     private String sexop;
     private String gruposangrep;
     private String estadop;
     private int idgruap;
     private int idmotovehiculop;

    public Personal() {
    }

    public Personal(int dnipersonal, String apellidop, String nombrep, Date fechanacimientop, String domiciliop, String nacionalidadp, Date fechaaltap, String sexop, String gruposangrep, String estadop, int idgruap, int idmotovehiculop) {
       this.dnipersonal = dnipersonal;
       this.apellidop = apellidop;
       this.nombrep = nombrep;
       this.fechanacimientop = fechanacimientop;
       this.domiciliop = domiciliop;
       this.nacionalidadp = nacionalidadp;
       this.fechaaltap = fechaaltap;
       this.sexop = sexop;
       this.gruposangrep = gruposangrep;
       this.estadop = estadop;
       this.idgruap = idgruap;
       this.idmotovehiculop = idmotovehiculop;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpersonal", unique=true, nullable=false)
    public Integer getIdpersonal() {
        return this.idpersonal;
    }
    
    public void setIdpersonal(Integer idpersonal) {
        this.idpersonal = idpersonal;
    }

    
    @Column(name="dnipersonal", nullable=false)
    public int getDnipersonal() {
        return this.dnipersonal;
    }
    
    public void setDnipersonal(int dnipersonal) {
        this.dnipersonal = dnipersonal;
    }

    
    @Column(name="apellidop", nullable=false, length=100)
    public String getApellidop() {
        return this.apellidop;
    }
    
    public void setApellidop(String apellidop) {
        this.apellidop = apellidop;
    }

    
    @Column(name="nombrep", nullable=false, length=100)
    public String getNombrep() {
        return this.nombrep;
    }
    
    public void setNombrep(String nombrep) {
        this.nombrep = nombrep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechanacimientop", nullable=false, length=10)
    public Date getFechanacimientop() {
        return this.fechanacimientop;
    }
    
    public void setFechanacimientop(Date fechanacimientop) {
        this.fechanacimientop = fechanacimientop;
    }

    
    @Column(name="domiciliop", nullable=false, length=150)
    public String getDomiciliop() {
        return this.domiciliop;
    }
    
    public void setDomiciliop(String domiciliop) {
        this.domiciliop = domiciliop;
    }

    
    @Column(name="nacionalidadp", nullable=false, length=30)
    public String getNacionalidadp() {
        return this.nacionalidadp;
    }
    
    public void setNacionalidadp(String nacionalidadp) {
        this.nacionalidadp = nacionalidadp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaaltap", nullable=false, length=10)
    public Date getFechaaltap() {
        return this.fechaaltap;
    }
    
    public void setFechaaltap(Date fechaaltap) {
        this.fechaaltap = fechaaltap;
    }

    
    @Column(name="sexop", nullable=false, length=2)
    public String getSexop() {
        return this.sexop;
    }
    
    public void setSexop(String sexop) {
        this.sexop = sexop;
    }

    
    @Column(name="gruposangrep", nullable=false, length=10)
    public String getGruposangrep() {
        return this.gruposangrep;
    }
    
    public void setGruposangrep(String gruposangrep) {
        this.gruposangrep = gruposangrep;
    }

    
    @Column(name="estadop", nullable=false, length=10)
    public String getEstadop() {
        return this.estadop;
    }
    
    public void setEstadop(String estadop) {
        this.estadop = estadop;
    }

    
    @Column(name="idgruap", nullable=false)
    public int getIdgruap() {
        return this.idgruap;
    }
    
    public void setIdgruap(int idgruap) {
        this.idgruap = idgruap;
    }

    
    @Column(name="idmotovehiculop", nullable=false)
    public int getIdmotovehiculop() {
        return this.idmotovehiculop;
    }
    
    public void setIdmotovehiculop(int idmotovehiculop) {
        this.idmotovehiculop = idmotovehiculop;
    }




}


