package modelo;
// Generated 20/05/2016 16:28:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RolMenu generated by hbm2java
 */
@Entity
@Table(name="rol_menu"
    ,catalog="transito"
)
public class RolMenu  implements java.io.Serializable {


     private Integer id;
     private int idrol;
     private int idmenu;

    public RolMenu() {
    }

    public RolMenu(int idrol, int idmenu) {
       this.idrol = idrol;
       this.idmenu = idmenu;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="idrol", nullable=false)
    public int getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(int idrol) {
        this.idrol = idrol;
    }

    
    @Column(name="idmenu", nullable=false)
    public int getIdmenu() {
        return this.idmenu;
    }
    
    public void setIdmenu(int idmenu) {
        this.idmenu = idmenu;
    }




}


