package modelo;
// Generated 20/05/2016 16:28:02 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="transito"
)
public class Usuarios  implements java.io.Serializable {


     private Integer idusuario;
     private String dniusuario;
     private String nombreusuario;
     private String paswordusuario;
     private int idrol;

    public Usuarios() {
    }

    public Usuarios(String dniusuario, String nombreusuario, String paswordusuario, int idrol) {
       this.dniusuario = dniusuario;
       this.nombreusuario = nombreusuario;
       this.paswordusuario = paswordusuario;
       this.idrol = idrol;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idusuario", unique=true, nullable=false)
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }

    
    @Column(name="dniusuario", nullable=false, length=100)
    public String getDniusuario() {
        return this.dniusuario;
    }
    
    public void setDniusuario(String dniusuario) {
        this.dniusuario = dniusuario;
    }

    
    @Column(name="nombreusuario", nullable=false, length=100)
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }

    
    @Column(name="paswordusuario", nullable=false, length=100)
    public String getPaswordusuario() {
        return this.paswordusuario;
    }
    
    public void setPaswordusuario(String paswordusuario) {
        this.paswordusuario = paswordusuario;
    }

    
    @Column(name="idrol", nullable=false)
    public int getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(int idrol) {
        this.idrol = idrol;
    }




}


